baseURL = "https://appablanca.github.io/trying_to_hear_the_music/"
theme = "PaperMod"

[params.homeInfoParams]
Title = "Trying to Hear the Music"
Content = "trying to build intuition and understand the approach"

[params]
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

